import { Catalog, type CatalogItem } from '../../../../domain/entities/Catalog'
import { BaseTMDBMapper } from '../base/BaseTMDBMapper'
import { TMDBMediaMapper } from './TMDBMediaMapper'
import { TMDBPersonMapper } from './TMDBPersonMapper'
import type {
  TMDBPaginatedResponse,
  TMDBMovieResponse,
  TMDBTVResponse,
  TMDBPersonResponse,
} from '../../../api/tmdb/types'
import type { TMDBConfigFactory } from '../../../factories/TMDBConfigFactory'

/**
 * Maps TMDB paginated responses to Catalog entities
 */
export class TMDBCatalogMapper extends BaseTMDBMapper {
  /**
   * Create movie catalog from TMDB movie search results
   */
  static fromMovieSearch(
    tmdbResponse: TMDBPaginatedResponse<TMDBMovieResponse>,
    query: string,
    configFactory?: TMDBConfigFactory
  ): Catalog {
    const items: CatalogItem[] = tmdbResponse.results.map((movie) => ({
      stableId: '', // Will be generated by Catalog constructor
      media: TMDBMediaMapper.fromMovie(movie, configFactory),
    }))

    return new Catalog({
      id: `tmdb-movie-search-${query}`,
      providerId: 'tmdb',
      name: `Movies: "${query}"`,
      type: 'movie',
      category: 'search',
      items,

      sourceInfo: {
        providerId: 'tmdb',
        apiVersion: 'v3',
        totalCount: tmdbResponse.total_results,
        lastUpdated: new Date(),
      },

      paginationInfo: {
        currentPage: tmdbResponse.page,
        totalPages: tmdbResponse.total_pages,
        hasMore: tmdbResponse.page < tmdbResponse.total_pages,
        offset: (tmdbResponse.page - 1) * 20,
        limit: 20,
      },
    })
  }

  /**
   * Create TV catalog from TMDB TV search results
   */
  static fromTVSearch(
    tmdbResponse: TMDBPaginatedResponse<TMDBTVResponse>,
    query: string,
    configFactory?: TMDBConfigFactory
  ): Catalog {
    const items: CatalogItem[] = tmdbResponse.results.map((tvShow) => ({
      stableId: '',
      media: TMDBMediaMapper.fromTV(tvShow, configFactory),
    }))

    return new Catalog({
      id: `tmdb-tv-search-${query}`,
      providerId: 'tmdb',
      name: `TV Shows: "${query}"`,
      type: 'series',
      category: 'search',
      items,

      sourceInfo: {
        providerId: 'tmdb',
        apiVersion: 'v3',
        totalCount: tmdbResponse.total_results,
        lastUpdated: new Date(),
      },

      paginationInfo: {
        currentPage: tmdbResponse.page,
        totalPages: tmdbResponse.total_pages,
        hasMore: tmdbResponse.page < tmdbResponse.total_pages,
        offset: (tmdbResponse.page - 1) * 20,
        limit: 20,
      },
    })
  }

  /**
   * Create people catalog from TMDB person search results
   */
  static fromPersonSearch(
    tmdbResponse: TMDBPaginatedResponse<TMDBPersonResponse>,
    query: string,
    configFactory?: TMDBConfigFactory
  ): Catalog {
    const items: CatalogItem[] = tmdbResponse.results.map((person) => ({
      stableId: '',
      person: TMDBPersonMapper.fromTMDB(person, configFactory),
    }))

    return new Catalog({
      id: `tmdb-person-search-${query}`,
      providerId: 'tmdb',
      name: `People: "${query}"`,
      type: 'person',
      category: 'search',
      items,

      sourceInfo: {
        providerId: 'tmdb',
        apiVersion: 'v3',
        totalCount: tmdbResponse.total_results,
        lastUpdated: new Date(),
      },

      paginationInfo: {
        currentPage: tmdbResponse.page,
        totalPages: tmdbResponse.total_pages,
        hasMore: tmdbResponse.page < tmdbResponse.total_pages,
        offset: (tmdbResponse.page - 1) * 20,
        limit: 20,
      },
    })
  }
}
